[".local/share/fonts/Fira Code Bold Nerd Font Complete.ttf"]
type = "file"
url = "https://github.com/ryanoasis/nerd-fonts/raw/master/patched-fonts/FiraCode/Bold/complete/Fira%20Code%20Bold%20Nerd%20Font%20Complete.ttf"
refreshPeriod = "168h"

[".local/share/fonts/Fira Code Bold Nerd Font Complete Mono.ttf"]
type = "file"
url = "https://github.com/ryanoasis/nerd-fonts/blob/master/patched-fonts/FiraCode/Bold/complete/Fira%20Code%20Bold%20Nerd%20Font%20Complete%20Mono.ttf"
refreshPeriod = "168h"

[".local/share/fonts/Fira Code Light Nerd Font Complete.ttf"]
type = "file"
url = "https://github.com/ryanoasis/nerd-fonts/raw/master/patched-fonts/FiraCode/Light/complete/Fira%20Code%20Light%20Nerd%20Font%20Complete.ttf"
refreshPeriod = "168h"

[".local/share/fonts/Fira Code Light Nerd Font Complete Mono.ttf"]
type = "file"
url = "https://github.com/ryanoasis/nerd-fonts/raw/master/patched-fonts/FiraCode/Light/complete/Fira%20Code%20Light%20Nerd%20Font%20Complete%20Mono.ttf"
refreshPeriod = "168h"

[".local/share/fonts/Fira Code Medium Nerd Font Complete.ttf"]
type = "file"
url = "https://github.com/ryanoasis/nerd-fonts/raw/master/patched-fonts/FiraCode/Medium/complete/Fira%20Code%20Medium%20Nerd%20Font%20Complete.ttf"
refreshPeriod = "168h"

[".local/share/fonts/Fira Code Medium Nerd Font Complete Mono.ttf"]
type = "file"
url = "https://github.com/ryanoasis/nerd-fonts/raw/master/patched-fonts/FiraCode/Medium/complete/Fira%20Code%20Medium%20Nerd%20Font%20Complete%20Mono.ttf"
refreshPeriod = "168h"

[".local/share/fonts/Fira Code Regular Nerd Font Complete.ttf"]
type = "file"
url = "https://github.com/ryanoasis/nerd-fonts/raw/master/patched-fonts/FiraCode/Regular/complete/Fira%20Code%20Regular%20Nerd%20Font%20Complete.ttf"
refreshPeriod = "168h"

[".local/share/fonts/Fira Code Regular Nerd Font Complete Mono.ttf"]
type = "file"
url = "https://github.com/ryanoasis/nerd-fonts/raw/master/patched-fonts/FiraCode/Regular/complete/Fira%20Code%20Regular%20Nerd%20Font%20Complete%20Mono.ttf"
refreshPeriod = "168h"

[".local/share/fonts/Fira Code Retina Nerd Font Complete.ttf"]
type = "file"
url = "https://github.com/ryanoasis/nerd-fonts/raw/master/patched-fonts/FiraCode/Retina/complete/Fira%20Code%20Retina%20Nerd%20Font%20Complete.ttf"
refreshPeriod = "168h"

[".local/share/fonts/Fira Code Retina Nerd Font Complete Mono.ttf"]
type = "file"
url = "https://github.com/ryanoasis/nerd-fonts/raw/master/patched-fonts/FiraCode/Retina/complete/Fira%20Code%20Retina%20Nerd%20Font%20Complete%20Mono.ttf"
refreshPeriod = "168h"

[".local/share/fonts/Fira Code SemiBold Nerd Font Complete.ttf"]
type = "file"
url = "https://github.com/ryanoasis/nerd-fonts/raw/master/patched-fonts/FiraCode/SemiBold/complete/Fira%20Code%20SemiBold%20Nerd%20Font%20Complete.ttf"
refreshPeriod = "168h"

[".local/share/fonts/Fira Code SemiBold Nerd Font Complete Mono.ttf"]
type = "file"
url = "https://github.com/ryanoasis/nerd-fonts/raw/master/patched-fonts/FiraCode/SemiBold/complete/Fira%20Code%20SemiBold%20Nerd%20Font%20Complete%20Mono.ttf"
refreshPeriod = "168h"
