[".local/share/fonts"]
type = "archive"
url = "https://github.com/ryanoasis/nerd-fonts/releases/latest/download/NerdFontsSymbolsOnly.zip"
refreshPeriod = "168h"
exclude = ["*.md", "*Windows Compatible.ttf"]
